#!/usr/bin/env python3
"""
AI Strategy Report Generator for ARIA v4.0
Generate professional disaster response recommendations using Google Gemini AI
"""

import os
import pandas as pd
from dotenv import load_dotenv
import google.generativeai as genai

# Load environment variables
load_dotenv()

def generate_ai_strategy_report():
    """Generate AI strategy report using Gemini API"""
    
    print("="*60)
    print("AI Strategy Report Generator")
    print("="*60)
    
    # Load analysis results
    try:
        accessibility_table = pd.read_csv("outputs/accessibility_impact_table.csv")
        print("   Accessibility impact table loaded successfully")
    except FileNotFoundError:
        print("   Error: Accessibility impact table not found")
        return False
    
    # Prepare data summary
    top_5_info = """
1. Node 649286213: Centrality = 0.1402
2. Node 649286214: Centrality = 0.1394  
3. Node 1061487893: Centrality = 0.1253
4. Node 929963021: Centrality = 0.1235
5. Node 1074772659: Centrality = 0.1157
"""
    
    iso_table_str = accessibility_table.to_string(index=False)
    
    # Extract key statistics
    avg_shrinkage_5min = 76.5
    avg_shrinkage_10min = 48.9
    most_vulnerable_node = "1061487893"
    
    # Prompt template for Gemini
    prompt = f"""
You are a transportation and disaster prevention advisor for the Hualien County Disaster Prevention Command Center.

Below are the road network analysis results under a heavy rainfall / typhoon scenario representing Typhoon Fung-wong conditions.

[Bottleneck Intersections: Top 5 Critical Transportation Hubs]
{top_5_info}

[Accessibility Impact Analysis Table]
{iso_table_str}

[Key Statistics]
- Average 5-minute accessibility shrinkage: {avg_shrinkage_5min}%
- Average 10-minute accessibility shrinkage: {avg_shrinkage_10min}%
- Most vulnerable hub: Node {most_vulnerable_node} (high centrality + terrain risk)
- Rainfall impact: 0.0 - 106.2 mm/hr with severe congestion effects

[Tasks]
Please provide a professional strategic report in Traditional Chinese. Your report should include:

1. **Priority Road Segments for Emergency Clearance**
   - Which specific bottlenecks should be cleared first
   - Reasoning based on centrality and accessibility impact
   - Estimated resource requirements

2. **Isolated Area Assessment**
   - Which areas are likely to become isolated based on accessibility reduction
   - Severity assessment (critical, high, medium, low)
   - Population impact estimation

3. **Alternative Rescue Methods**
   - Helicopter evacuation zones and priorities
   - Rubber boat deployment for flooded areas
   - Temporary shelter locations and supply routes
   - Emergency communication restoration methods

4. **Resource Allocation Priority Order**
   - Immediate (0-6 hours)
   - Short-term (6-24 hours)  
   - Medium-term (24-72 hours)
   - Long-term (72+ hours)

5. **Overall Disaster Response Strategy**
   - Coordination between different agencies
   - Public communication strategy
   - Evacuation timeline and procedures
   - Recovery and restoration priorities

Please format the response with clear headings, bullet points, and professional terminology appropriate for government disaster management. Include specific actionable recommendations that can be implemented immediately.

Focus on practical, realistic solutions that consider Hualien County's geographic constraints (mountainous terrain, coastal areas, limited transportation infrastructure).
"""
    
    # Configure Gemini API
    api_key = os.getenv("Gemini_API_Key")
    if not api_key:
        print("   Error: Gemini_API_Key not found in .env file")
        return False
    
    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel("models/gemini-2.5-flash-lite")
        
        print("   Gemini AI model initialized successfully")
        print("   Generating strategy report...")
        
        # Generate AI response
        response = model.generate_content(prompt)
        
        # Save AI report
        with open('outputs/ai_strategy_report.txt', 'w', encoding='utf-8') as f:
            f.write("="*80 + "\n")
            f.write("ARIA v4.0 - AI Generated Disaster Response Strategy Report\n")
            f.write("Generated by Google Gemini AI\n")
            f.write(f"Date: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
            f.write("="*80 + "\n\n")
            f.write(response.text)
        
        print("   AI strategy report saved to outputs/ai_strategy_report.txt")
        
        # Generate summary
        with open('outputs/ai_report_summary.txt', 'w', encoding='utf-8') as f:
            f.write("AI Strategy Report Generation Summary\n")
            f.write("="*40 + "\n")
            f.write(f"Model: Gemini 2.5 Flash Lite\n")
            f.write(f"Data used: Accessibility impact table with 5 facilities\n")
            f.write(f"Key metrics: {avg_shrinkage_5min}% avg 5-min shrinkage\n")
            f.write(f"Report length: {len(response.text)} characters\n")
            f.write(f"Generated at: {pd.Timestamp.now().strftime('%Y-%m-%d %H:%M:%S')}\n")
        
        print("   AI report summary saved to outputs/ai_report_summary.txt")
        
        return True
        
    except Exception as e:
        print(f"   Error generating AI report: {e}")
        return False

if __name__ == "__main__":
    success = generate_ai_strategy_report()
    
    if success:
        print("\n" + "="*60)
        print("AI Strategy Report Generation Complete!")
        print("Files generated:")
        print("  - outputs/ai_strategy_report.txt (Full report)")
        print("  - outputs/ai_report_summary.txt (Generation summary)")
        print("="*60)
    else:
        print("\nAI Strategy Report Generation Failed!")
        print("Please check API key and internet connection.")
